In [21]:
# tensorflow version
import tensorflow as tf
# import load_iris
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical
import autokeras as ak
print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.10.0


In [22]:

# Load the dataset
iris = load_iris()
X = iris.data
y = iris.target
model_name = 'iris_classifier'
# Convert target to categorical data
#TODO leerling; kijke even wat er gebeurt als dit wel uitvoerd
y = to_categorical(y)

In [38]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [23]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [24]:
# Initialize the AutoKeras classifier with HyperModel and perform hyperparameter tuning
clf = ak.StructuredDataClassifier(overwrite=True, max_trials=10, loss="CategoricalCrossentropy")  # Hyperparameter tuning for 20 trials

# Search for the best model and hyperparameters
clf.fit(X_train, y_train, epochs=100, validation_split=0.2)

# Evaluate the best model
score = clf.evaluate(X_test, y_test)
print("Test Accuracy:", score[1])

Trial 10 Complete [00h 00m 06s]
val_accuracy: 0.9583333134651184

Best val_accuracy So Far: 0.9583333134651184
Total elapsed time: 00h 00m 59s
Epoch 1/100
4/4 [==============================] - 0s 4ms/step - loss: 1.0811 - accuracy: 0.3583
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0027 - accuracy: 0.5250
Epoch 3/100
4/4 [==============================] - 0s 4ms/step - loss: 0.9323 - accuracy: 0.6750
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 0.8675 - accuracy: 0.7583
Epoch 5/100
4/4 [==============================] - 0s 4ms/step - loss: 0.8080 - accuracy: 0.7833
Epoch 6/100
4/4 [==============================] - 0s 4ms/step - loss: 0.7533 - accuracy: 0.7917
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 0.7029 - accuracy: 0.7917
Epoch 8/100
4/4 [==============================] - 0s 4ms/step - loss: 0.6563 - accuracy: 0.8167
Epoch 9/100
4/4 [==============================] - 0s 4ms/step - loss: 0.6131 - a

In [25]:
# export model
model = clf.export_model()
# save as h5
model.save(model_name + '.h5')
model.summary()


Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 multi_category_encoding (Mu  (None, 4)                0         
 ltiCategoryEncoding)                                            
                                                                 
 normalization (Normalizatio  (None, 4)                9         
 n)                                                              
                                                                 
 dense (Dense)               (None, 32)                160       
                                                                 
 re_lu (ReLU)                (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 32)                1056  

In [35]:
# load model
model = tf.keras.models.load_model(model_name + '.h5', custom_objects=ak.CUSTOM_OBJECTS)
y_pred = model.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)
# y_test_decoded = np.argmax(y_test, axis=1)
print(y_pred)

1/1 [==============================] - 0s 75ms/step
[[3.05980258e-03 9.68143046e-01 2.87971180e-02]
 [9.98551548e-01 1.33020384e-03 1.18155120e-04]
 [5.05839282e-09 5.75242448e-05 9.99942422e-01]
 [5.74046280e-03 8.23284984e-01 1.70974523e-01]
 [4.76627582e-04 9.38972771e-01 6.05506226e-02]
 [9.97469187e-01 2.41554156e-03 1.15284260e-04]
 [1.94065385e-02 9.72938657e-01 7.65477354e-03]
 [1.99468068e-05 4.56466619e-03 9.95415330e-01]
 [8.37183179e-05 6.97312236e-01 3.02604049e-01]
 [3.13271326e-03 9.92045641e-01 4.82157571e-03]
 [7.29024294e-04 5.94484806e-02 9.39822555e-01]
 [9.98127639e-01 1.84035848e-03 3.20565123e-05]
 [9.98982251e-01 9.71419562e-04 4.63214310e-05]
 [9.98192251e-01 1.76912604e-03 3.86716238e-05]
 [9.99553025e-01 3.87807057e-04 5.90722993e-05]
 [1.75916087e-02 8.23207080e-01 1.59201339e-01]
 [8.47242245e-06 1.26421673e-03 9.98727262e-01]
 [1.68713368e-03 9.95513856e-01 2.79911119e-03]
 [6.64236350e-03 9.44503009e-01 4.88546230e-02]
 [3.71666238e-06 7.99827569e-04 9.99

In [36]:
np.argmax(y_pred, axis=1)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)

In [31]:
for i in range(len(y_pred)):
    print(y_pred[i], y_test[i])

[0.0030598  0.96814305 0.02879712] [0. 1. 0.]
[9.9855155e-01 1.3302038e-03 1.1815512e-04] [1. 0. 0.]
[5.0583928e-09 5.7524245e-05 9.9994242e-01] [0. 0. 1.]
[0.00574046 0.823285   0.17097452] [0. 1. 0.]
[4.7662758e-04 9.3897277e-01 6.0550623e-02] [0. 1. 0.]
[9.9746919e-01 2.4155416e-03 1.1528426e-04] [1. 0. 0.]
[0.01940654 0.97293866 0.00765477] [0. 1. 0.]
[1.9946807e-05 4.5646662e-03 9.9541533e-01] [0. 0. 1.]
[8.3718318e-05 6.9731224e-01 3.0260405e-01] [0. 1. 0.]
[0.00313271 0.99204564 0.00482158] [0. 1. 0.]
[7.2902429e-04 5.9448481e-02 9.3982255e-01] [0. 0. 1.]
[9.9812764e-01 1.8403585e-03 3.2056512e-05] [1. 0. 0.]
[9.9898225e-01 9.7141956e-04 4.6321431e-05] [1. 0. 0.]
[9.9819225e-01 1.7691260e-03 3.8671624e-05] [1. 0. 0.]
[9.9955302e-01 3.8780706e-04 5.9072299e-05] [1. 0. 0.]
[0.01759161 0.8232071  0.15920134] [0. 1. 0.]
[8.4724225e-06 1.2642167e-03 9.9872726e-01] [0. 0. 1.]
[0.00168713 0.99551386 0.00279911] [0. 1. 0.]
[0.00664236 0.944503   0.04885462] [0. 1. 0.]
[3.7166624e-06 7.9

In [32]:
# save as h5 model
model.save("model_autokeras2.h5")
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 4)]               0         
                                                                 
 multi_category_encoding (Mu  (None, 4)                0         
 ltiCategoryEncoding)                                            


                                                                 
 normalization (Normalizatio  (None, 4)                9         
 n)                                                              
                                                                 
 dense (Dense)               (None, 32)                160       
                                                                 
 re_lu (ReLU)                (None, 32)                0         
                                                                 
 dense_1 (Dense)             (None, 32)                1056      
                                                                 
 re_lu_1 (ReLU)              (None, 32)                0         
                                                                 
 dense_2 (Dense)             (None, 3)                 99        
                                                                 
 classification_head_1 (Soft  (None, 3)                0         
 max)     

In [33]:
model_h5 = tf.keras.models.load_model("model_autokeras2.h5")
y_pred = model_h5.predict(X_test)
y_pred = np.argmax(y_pred, axis=1)
y_pred

1/1 [==============================] - 0s 78ms/step


array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0], dtype=int64)